In [5]:
import pandas as pd
temp_file = pd.HDFStore("data/kite_cache_day.h5", mode="r")

In [2]:
df = pd.read_csv('data/ind_nifty50list.csv')
pd.DataFrame({'label':df['Symbol'],'value':df['Symbol']}).to_dict(orient='records')

In [20]:
pd.DataFrame({'label':df['Symbol'],'value':df['Symbol']}).to_dict(orient='records')

[{'label': 'ADANIPORTS', 'value': 'ADANIPORTS'},
 {'label': 'ASIANPAINT', 'value': 'ASIANPAINT'},
 {'label': 'AXISBANK', 'value': 'AXISBANK'},
 {'label': 'BAJAJ-AUTO', 'value': 'BAJAJ-AUTO'},
 {'label': 'BAJFINANCE', 'value': 'BAJFINANCE'},
 {'label': 'BAJAJFINSV', 'value': 'BAJAJFINSV'},
 {'label': 'BPCL', 'value': 'BPCL'},
 {'label': 'BHARTIARTL', 'value': 'BHARTIARTL'},
 {'label': 'INFRATEL', 'value': 'INFRATEL'},
 {'label': 'BRITANNIA', 'value': 'BRITANNIA'},
 {'label': 'CIPLA', 'value': 'CIPLA'},
 {'label': 'COALINDIA', 'value': 'COALINDIA'},
 {'label': 'DRREDDY', 'value': 'DRREDDY'},
 {'label': 'EICHERMOT', 'value': 'EICHERMOT'},
 {'label': 'GAIL', 'value': 'GAIL'},
 {'label': 'GRASIM', 'value': 'GRASIM'},
 {'label': 'HCLTECH', 'value': 'HCLTECH'},
 {'label': 'HDFCBANK', 'value': 'HDFCBANK'},
 {'label': 'HEROMOTOCO', 'value': 'HEROMOTOCO'},
 {'label': 'HINDALCO', 'value': 'HINDALCO'},
 {'label': 'HINDUNILVR', 'value': 'HINDUNILVR'},
 {'label': 'HDFC', 'value': 'HDFC'},
 {'label': 'ITC', 'value': 'ITC'},
 {'label': 'ICICIBANK', 'value': 'ICICIBANK'},
 {'label': 'IBULHSGFIN', 'value': 'IBULHSGFIN'},
 {'label': 'IOC', 'value': 'IOC'},
 {'label': 'INDUSINDBK', 'value': 'INDUSINDBK'},
 {'label': 'INFY', 'value': 'INFY'},
 {'label': 'JSWSTEEL', 'value': 'JSWSTEEL'},
 {'label': 'KOTAKBANK', 'value': 'KOTAKBANK'},
 {'label': 'LT', 'value': 'LT'},
 {'label': 'M&M', 'value': 'M&M'},
 {'label': 'MARUTI', 'value': 'MARUTI'},
 {'label': 'NTPC', 'value': 'NTPC'},
 {'label': 'ONGC', 'value': 'ONGC'},
 {'label': 'POWERGRID', 'value': 'POWERGRID'},
 {'label': 'RELIANCE', 'value': 'RELIANCE'},
 {'label': 'SBIN', 'value': 'SBIN'},
 {'label': 'SUNPHARMA', 'value': 'SUNPHARMA'},
 {'label': 'TCS', 'value': 'TCS'},
 {'label': 'TATAMOTORS', 'value': 'TATAMOTORS'},
 {'label': 'TATASTEEL', 'value': 'TATASTEEL'},
 {'label': 'TECHM', 'value': 'TECHM'},
 {'label': 'TITAN', 'value': 'TITAN'},
 {'label': 'UPL', 'value': 'UPL'},
 {'label': 'ULTRACEMCO', 'value': 'ULTRACEMCO'},
 {'label': 'VEDL', 'value': 'VEDL'},
 {'label': 'WIPRO', 'value': 'WIPRO'},
 {'label': 'YESBANK', 'value': 'YESBANK'},
 {'label': 'ZEEL', 'value': 'ZEEL'}]

In [2]:
temp_file = pd.HDFStore("data/kite_data_v1.h5", mode="r")
temp_file.keys()

In [7]:
temp_file.get('NSE')

,instrument_token,exchange_token,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange
tradingsymbol,,,,,,,,,,,
NIFTY SMALL 100,264201,1032,NIFTY SMALL 100,0.0,,0.0,0.00,0,EQ,NSE-INDICES,NSE
NIFTY SMALL 100,264201,1032,NIFTY SMALL 100,0.0,,0.0,0.00,0,EQ,INDICES,NSE
NIFTY INFRA,261385,1021,NIFTY INFRA,0.0,,0.0,0.00,0,EQ,NSE-INDICES,NSE
NIFTY INFRA,261385,1021,NIFTY INFRA,0.0,,0.0,0.00,0,EQ,INDICES,NSE
NIFTY50 DIV POINT,265225,1036,NIFTY50 DIV POINT,0.0,,0.0,0.00,0,EQ,NSE-INDICES,NSE
...,...,...,...,...,...,...,...,...,...,...,...
AKG-SM,1225217,4786,,0.0,,0.0,0.05,4000,EQ,NSE,NSE
CINELINE,6953217,27161,CINELINE INDIA,0.0,,0.0,0.05,1,EQ,NSE,NSE
CIMMCO,6447105,25184,CIMMCO,0.0,,0.0,0.05,1,EQ,NSE,NSE
CIGNITITEC,1316353,5142,,0.0,,0.0,0.05,1,EQ,NSE,NSE
CHOLAFIN,175361,685,CHOLAMANDALAM IN & FIN CO,0.0,,0.0,0.05,1,EQ,NSE,NSE

In [3]:
temp_file.keys()

['/NSE',
 '/day/NSE/3MINDIA',
 '/day/NSE/AARTIIND',
 '/day/NSE/ABB',
 '/day/NSE/ABFRL',
 '/day/NSE/ACC',
 '/day/NSE/ACE',
 '/day/NSE/ADANIENT',
 '/day/NSE/ADANIPORTS',
 '/day/NSE/ADANIPOWER',
 '/day/NSE/AIAENG',
 '/day/NSE/AJANTPHARM',
 '/day/NSE/AKZOINDIA',
 '/day/NSE/ALBK',
 '/day/NSE/ALKEM',
 '/day/NSE/ALLCARGO',
 '/day/NSE/AMARAJABAT',
 '/day/NSE/AMBUJACEM',
 '/day/NSE/ANANTRAJ',
 '/day/NSE/APOLLOHOSP',
 '/day/NSE/APOLLOTYRE',
 '/day/NSE/ARVIND',
 '/day/NSE/ASAHIINDIA',
 '/day/NSE/ASHOKLEY',
 '/day/NSE/ASIANPAINT',
 '/day/NSE/ASTRAZEN',
 '/day/NSE/ATFL',
 '/day/NSE/ATUL',
 '/day/NSE/AUBANK',
 '/day/NSE/AUROPHARMA',
 '/day/NSE/AUTOAXLES',
 '/day/NSE/AVANTIFEED',
 '/day/NSE/AXISBANK',
 '/day/NSE/BAJAJ-AUTO',
 '/day/NSE/BAJAJELEC',
 '/day/NSE/BAJAJFINSV',
 '/day/NSE/BAJAJHLDNG',
 '/day/NSE/BAJFINANCE',
 '/day/NSE/BALKRISIND',
 '/day/NSE/BALRAMCHIN',
 '/day/NSE/BANCOINDIA',
 '/day/NSE/BANKBARODA',
 '/day/NSE/BANKBEES',
 '/day/NSE/BANKINDIA',
 '/day/NSE/BATAINDIA',
 '/day/NSE/BBTC',
 '/day/NSE/BEL',
 '/day/NSE/BEML',
 '/day/NSE/BERGEPAINT',
 '/day/NSE/BFUTILITIE',
 '/day/NSE/BHARATFIN',
 '/day/NSE/BHARATFORG',
 '/day/NSE/BHARTIARTL',
 '/day/NSE/BHEL',
 '/day/NSE/BIOCON',
 '/day/NSE/BLISSGVS',
 '/day/NSE/BLKASHYAP',
 '/day/NSE/BLUEDART',
 '/day/NSE/BOSCHLTD',
 '/day/NSE/BPCL',
 '/day/NSE/BRITANNIA',
 '/day/NSE/BSE',
 '/day/NSE/CADILAHC',
 '/day/NSE/CAMLINFINE',
 '/day/NSE/CANBK',
 '/day/NSE/CANFINHOME',
 '/day/NSE/CAPACITE',
 '/day/NSE/CASTROLIND',
 '/day/NSE/CDSL',
 '/day/NSE/CEATLTD',
 '/day/NSE/CENTRUM',
 '/day/NSE/CENTURYPLY',
 '/day/NSE/CENTURYTEX',
 '/day/NSE/CEREBRAINT',
 '/day/NSE/CESC',
 '/day/NSE/CGCL',
 '/day/NSE/CGPOWER',
 '/day/NSE/CHENNPETRO',
 '/day/NSE/CHOLAFIN',
 '/day/NSE/CIPLA',
 '/day/NSE/CNOVAPETRO',
 '/day/NSE/COALINDIA',
 '/day/NSE/COCHINSHIP',
 '/day/NSE/COFFEEDAY',
 '/day/NSE/COLPAL',
 '/day/NSE/CONCOR',
 '/day/NSE/COROMANDEL',
 '/day/NSE/COX&KINGS',
 '/day/NSE/CRISIL',
 '/day/NSE/CROMPTON',
 '/day/NSE/CUB',
 '/day/NSE/CUMMINSIND',
 '/day/NSE/CYIENT',
 '/day/NSE/DAAWAT',
 '/day/NSE/DABUR',
 '/day/NSE/DALMIASUG',
 '/day/NSE/DBCORP',
 '/day/NSE/DCBBANK',
 '/day/NSE/DCMSHRIRAM',
 '/day/NSE/DEN',
 '/day/NSE/DHAMPURSUG',
 '/day/NSE/DHFL',
 '/day/NSE/DIAMONDYD',
 '/day/NSE/DISHTV',
 '/day/NSE/DIVISLAB',
 '/day/NSE/DIXON',
 '/day/NSE/DLF',
 '/day/NSE/DMART',
 '/day/NSE/DREDGECORP',
 '/day/NSE/DRREDDY',
 '/day/NSE/ECLERX',
 '/day/NSE/EICHERMOT',
 '/day/NSE/EIDPARRY',
 '/day/NSE/EIHOTEL',
 '/day/NSE/ELECTCAST',
 '/day/NSE/EMAMILTD',
 '/day/NSE/ENDURANCE',
 '/day/NSE/ENGINERSIN',
 '/day/NSE/EQUITAS',
 '/day/NSE/ERIS',
 '/day/NSE/EROSMEDIA',
 '/day/NSE/ESCORTS',
 '/day/NSE/ESTER',
 '/day/NSE/EXIDEIND',
 '/day/NSE/FEDERALBNK',
 '/day/NSE/FEL',
 '/day/NSE/FINCABLES',
 '/day/NSE/FORTIS',
 '/day/NSE/FRETAIL',
 '/day/NSE/GAIL',
 '/day/NSE/GATI',
 '/day/NSE/GDL',
 '/day/NSE/GEPIL',
 '/day/NSE/GESHIP',
 '/day/NSE/GET&D',
 '/day/NSE/GHCL',
 '/day/NSE/GICHSGFIN',
 '/day/NSE/GICRE',
 '/day/NSE/GILLETTE',
 '/day/NSE/GLAXO',
 '/day/NSE/GLENMARK',
 '/day/NSE/GLOBUSSPR',
 '/day/NSE/GMBREW',
 '/day/NSE/GMRINFRA',
 '/day/NSE/GNA',
 '/day/NSE/GNFC',
 '/day/NSE/GODFRYPHLP',
 '/day/NSE/GODREJAGRO',
 '/day/NSE/GODREJCP',
 '/day/NSE/GODREJIND',
 '/day/NSE/GODREJPROP',
 '/day/NSE/GOLDBEES',
 '/day/NSE/GPPL',
 '/day/NSE/GRANULES',
 '/day/NSE/GRASIM',
 '/day/NSE/GREAVESCOT',
 '/day/NSE/GSFC',
 '/day/NSE/GSKCONS',
 '/day/NSE/GSPL',
 '/day/NSE/GUJALKALI',
 '/day/NSE/GUJFLUORO',
 '/day/NSE/GUJGASLTD',
 '/day/NSE/HATHWAY',
 '/day/NSE/HAVELLS',
 '/day/NSE/HBLPOWER',
 '/day/NSE/HCL-INSYS',
 '/day/NSE/HCLTECH',
 '/day/NSE/HDFC',
 '/day/NSE/HDFCAMC',
 '/day/NSE/HDFCBANK',
 '/day/NSE/HDFCLIFE',
 '/day/NSE/HEIDELBERG',
 '/day/NSE/HEROMOTOCO',
 '/day/NSE/HEXAWARE',
 '/day/NSE/HGS',
 '/day/NSE/HIKAL',
 '/day/NSE/HINDALCO',
 '/day/NSE/HINDCOPPER',
 '/day/NSE/HINDPETRO',
 '/day/NSE/HINDUNILVR',
 '/day/NSE/HINDZINC',
 '/day/NSE/HONAUT',
 '/day/NSE/HSCL',
 '/day/NSE/HSIL',
 '/day/NSE/HUDCO',
 '/day/NSE/IBULHSGFIN',
 '/day/NSE/ICICIBANK',
 '/day/NSE/ICICIGI',
 '/day/NSE/ICICINIFTY',
 '/day/NSE/ICICIPRULI',
 '/day/NSE/IDBI',
 '/day/NSE/IDEA',
 '/day/NSE/IDFC',
 '/day/NSE/IDFCFIRSTB',
 '/day/NSE/IEX',
 '/day/NSE/IFCI',
 '/day/NSE/IGL',
 '/day/NSE/INDHOTEL',
 '/day/NSE/INDIACEM',
 '/day/NSE/INDIANB',
 '/day/NSE/INDIGO',
 '/day/NSE/INDUSINDBK',
 '/day/NSE/INFIBEAM',
 '/day/NSE/INFRATEL',
 '/day/NSE/INFY',
 '/day/NSE/INOXLEISUR',
 '/day/NSE/INOXWIND',
 '/day/NSE/INTELLECT',
 '/day/NSE/IOB',
 '/day/NSE/IOC',
 '/day/NSE/IPCALAB',
 '/day/NSE/IRB',
 '/day/NSE/ITC',
 '/day/NSE/ITDCEM',
 '/day/NSE/JAGRAN',
 '/day/NSE/JAICORPLTD',
 '/day/NSE/JAMNAAUTO',
 '/day/NSE/JAYAGROGN',
 '/day/NSE/JAYSREETEA',
 '/day/NSE/JETAIRWAYS',
 '/day/NSE/JINDALSTEL',
 '/day/NSE/JINDWORLD',
 '/day/NSE/JISLJALEQS',
 '/day/NSE/JKCEMENT',
 '/day/NSE/JKPAPER',
 '/day/NSE/JKTYRE',
 '/day/NSE/JMFINANCIL',
 '/day/NSE/JPASSOCIAT',
 '/day/NSE/JSLHISAR',
 '/day/NSE/JSWENERGY',
 '/day/NSE/JSWSTEEL',
 '/day/NSE/JUBILANT',
 '/day/NSE/JUBLFOOD',
 '/day/NSE/JUSTDIAL',
 '/day/NSE/JYOTHYLAB',
 '/day/NSE/KAJARIACER',
 '/day/NSE/KALPATPOWR',
 '/day/NSE/KANSAINER',
 '/day/NSE/KARURVYSYA',
 '/day/NSE/KEC',
 '/day/NSE/KEI',
 '/day/NSE/KILITCH',
 '/day/NSE/KIRIINDUS',
 '/day/NSE/KOTAKBANK',
 '/day/NSE/KOTAKNIFTY',
 '/day/NSE/KSCL',
 '/day/NSE/KTKBANK',
 '/day/NSE/L&TFH',
 '/day/NSE/LALPATHLAB',
 '/day/NSE/LIBERTSHOE',
 '/day/NSE/LICHSGFIN',
 '/day/NSE/LINCOLN',
 '/day/NSE/LIQUIDBEES',
 '/day/NSE/LOVABLE',
 '/day/NSE/LT',
 '/day/NSE/LUPIN',
 '/day/NSE/M&M',
 '/day/NSE/M&MFIN',
 '/day/NSE/M50',
 '/day/NSE/MAGMA',
 '/day/NSE/MAHINDCIE',
 '/day/NSE/MAHLOG',
 '/day/NSE/MAHSEAMLES',
 '/day/NSE/MAJESCO',
 '/day/NSE/MANALIPETC',
 '/day/NSE/MANAPPURAM',
 '/day/NSE/MANGTIMBER',
 '/day/NSE/MANINDS',
 '/day/NSE/MANINFRA',
 '/day/NSE/MARICO',
 '/day/NSE/MARKSANS',
 '/day/NSE/MARUTI',
 '/day/NSE/MASFIN',
 '/day/NSE/MASTEK',
 '/day/NSE/MCDOWELL-N',
 '/day/NSE/MCX',
 '/day/NSE/MEGH',
 '/day/NSE/MFSL',
 '/day/NSE/MGL',
 '/day/NSE/MIDHANI',
 '/day/NSE/MINDACORP',
 '/day/NSE/MINDAIND',
 '/day/NSE/MINDTREE',
 '/day/NSE/MMTC',
 '/day/NSE/MOIL',
 '/day/NSE/MOLDTKPAC',
 '/day/NSE/MOREPENLAB',
 '/day/NSE/MOTHERSUMI',
 '/day/NSE/MPHASIS',
 '/day/NSE/MRF',
 '/day/NSE/MRPL',
 '/day/NSE/MUKANDLTD',
 '/day/NSE/MUNJALAU',
 '/day/NSE/MUTHOOTFIN',
 '/day/NSE/NATCOPHARM',
 '/day/NSE/NATIONALUM',
 '/day/NSE/NAUKRI',
 '/day/NSE/NAVINFLUOR',
 '/day/NSE/NAVNETEDUL',
 '/day/NSE/NBCC',
 '/day/NSE/NCC',
 '/day/NSE/NESTLEIND',
 '/day/NSE/NETWORK18',
 '/day/NSE/NFL',
 '/day/NSE/NH',
 '/day/NSE/NHPC',
 '/day/NSE/NIACL',
 '/day/NSE/NIFTYBEES',
 '/day/NSE/NIITTECH',
 '/day/NSE/NLCINDIA',
 '/day/NSE/NMDC',
 '/day/NSE/NOCIL',
 '/day/NSE/NRBBEARING',
 '/day/NSE/NTPC',
 '/day/NSE/OBEROIRLTY',
 '/day/NSE/OFSS',
 '/day/NSE/OIL',
 '/day/NSE/OMAXE',
 '/day/NSE/ONGC',
 '/day/NSE/ORIENTBANK',
 '/day/NSE/ORIENTCEM',
 '/day/NSE/PAGEIND',
 '/day/NSE/PAPERPROD',
 '/day/NSE/PARAGMILK',
 '/day/NSE/PATELENG',
 '/day/NSE/PCJEWELLER',
 '/day/NSE/PEL',
 '/day/NSE/PERSISTENT',
 '/day/NSE/PETRONET',
 '/day/NSE/PFC',
 '/day/NSE/PFIZER',
 '/day/NSE/PGHH',
 '/day/NSE/PHILIPCARB',
 '/day/NSE/PHOENIXLTD',
 '/day/NSE/PIDILITIND',
 '/day/NSE/PIIND',
 '/day/NSE/PNB',
 '/day/NSE/PNBGILTS',
 '/day/NSE/PNBHOUSING',
 '/day/NSE/POLYPLEX',
 '/day/NSE/POWERGRID',
 '/day/NSE/PRAJIND',
 '/day/NSE/PRESTIGE',
 '/day/NSE/PTC',
 '/day/NSE/PURVA',
 '/day/NSE/PVR',
 '/day/NSE/QUICKHEAL',
 '/day/NSE/RADICO',
 '/day/NSE/RADIOCITY',
 '/day/NSE/RAJESHEXPO',
 '/day/NSE/RALLIS',
 '/day/NSE/RAMCOCEM',
 '/day/NSE/RAMCOIND',
 '/day/NSE/RAMKY',
 '/day/NSE/RAYMOND',
 '/day/NSE/RBLBANK',
 '/day/NSE/RCF',
 '/day/NSE/RECLTD',
 '/day/NSE/RELAXO',
 '/day/NSE/RELCAPITAL',
 '/day/NSE/RELIANCE',
 '/day/NSE/RELINFRA',
 '/day/NSE/REPCOHOME',
 '/day/NSE/RICOAUTO',
 '/day/NSE/RIIL',
 '/day/NSE/RKFORGE',
 '/day/NSE/RPOWER',
 '/day/NSE/SAIL',
 '/day/NSE/SAKUMA',
 '/day/NSE/SALASAR',
 '/day/NSE/SALZERELEC',
 '/day/NSE/SANGHIIND',
 '/day/NSE/SANGHVIMOV',
 '/day/NSE/SANOFI',
 '/day/NSE/SAREGAMA',
 '/day/NSE/SBILIFE',
 '/day/NSE/SBIN',
 '/day/NSE/SCHAEFFLER',
 '/day/NSE/SCHAND',
 '/day/NSE/SCHNEIDER',
 '/day/NSE/SCI',
 '/day/NSE/SELAN',
 '/day/NSE/SEQUENT',
 '/day/NSE/SHARDAMOTR',
 '/day/NSE/SHREECEM',
 '/day/NSE/SHRIRAMCIT',
 '/day/NSE/SIEMENS',
 '/day/NSE/SIMPLEXINF',
 '/day/NSE/SINTEX',
 '/day/NSE/SIS',
 '/day/NSE/SJVN',
 '/day/NSE/SKFINDIA',
 '/day/NSE/SNOWMAN',
 '/day/NSE/SOBHA',
 '/day/NSE/SOLARINDS',
 '/day/NSE/SOUTHBANK',
 '/day/NSE/SPARC',
 '/day/NSE/SPTL',
 '/day/NSE/SREINFRA',
 '/day/NSE/SRF',
 '/day/NSE/SRTRANSFIN',
 '/day/NSE/STAR',
 '/day/NSE/STCINDIA',
 '/day/NSE/STRTECH',
 '/day/NSE/SUNDARMFIN',
 '/day/NSE/SUNDRMFAST',
 '/day/NSE/SUNPHARMA',
 '/day/NSE/SUNTECK',
 '/day/NSE/SUNTV',
 '/day/NSE/SUPREMEIND',
 '/day/NSE/SUVEN',
 '/day/NSE/SUZLON',
 '/day/NSE/SYNDIBANK',
 '/day/NSE/SYNGENE',
 '/day/NSE/TAKE',
 '/day/NSE/TALWALKARS',
 '/day/NSE/TATACHEM',
 '/day/NSE/TATACOFFEE',
 '/day/NSE/TATACOMM',
 '/day/NSE/TATAELXSI',
 '/day/NSE/TATAGLOBAL',
 '/day/NSE/TATAINVEST',
 '/day/NSE/TATAMOTORS',
 '/day/NSE/TATAMTRDVR',
 '/day/NSE/TATAPOWER',
 '/day/NSE/TATASPONGE',
 '/day/NSE/TATASTEEL',
 '/day/NSE/TBZ',
 '/day/NSE/TCI',
 '/day/NSE/TCS',
 '/day/NSE/TECHM',
 '/day/NSE/TEJASNET',
 '/day/NSE/TEXMOPIPES',
 '/day/NSE/TEXRAIL',
 '/day/NSE/THERMAX',
 '/day/NSE/THOMASCOOK',
 '/day/NSE/THYROCARE',
 '/day/NSE/TIMETECHNO',
 '/day/NSE/TINPLATE',
 '/day/NSE/TITAN',
 '/day/NSE/TNPETRO',
 '/day/NSE/TNPL',
 '/day/NSE/TORNTPHARM',
 '/day/NSE/TORNTPOWER',
 '/day/NSE/TRENT',
 '/day/NSE/TRIDENT',
 '/day/NSE/TRIGYN',
 '/day/NSE/TRIVENI',
 '/day/NSE/TTKPRESTIG',
 '/day/NSE/TV18BRDCST',
 '/day/NSE/TVSMOTOR',
 '/day/NSE/TWL',
 '/day/NSE/UBL',
 '/day/NSE/UCOBANK',
 '/day/NSE/UJJIVAN',
 '/day/NSE/ULTRACEMCO',
 '/day/NSE/UNIONBANK',
 '/day/NSE/UNIVCABLES',
 '/day/NSE/UPL',
 '/day/NSE/USHAMART',
 '/day/NSE/VEDL',
 '/day/NSE/VGUARD',
 '/day/NSE/VIPCLOTHNG',
 '/day/NSE/VIPIND',
 '/day/NSE/VOLTAS',
 '/day/NSE/VTL',
 '/day/NSE/WABCOINDIA',
 '/day/NSE/WALCHANNAG',
 '/day/NSE/WELCORP',
 '/day/NSE/WELENT',
 '/day/NSE/WELSPUNIND',
 '/day/NSE/WHIRLPOOL',
 '/day/NSE/WINDMACHIN',
 '/day/NSE/WIPRO',
 '/day/NSE/WOCKPHARMA',
 '/day/NSE/WONDERLA',
 '/day/NSE/YESBANK',
 '/day/NSE/ZEEL']

In [13]:
temp_file.get('/day/NSE/WIPRO')

             close    high     low    open    volume
date
2009-05-07   75.56   76.26   69.98   71.36   9338100
2009-05-08   70.39   76.02   69.87   75.72   9197010
2009-05-11   69.30   71.36   67.42   70.77   4109066
2009-05-12   74.23   75.08   68.39   68.98   7708026
2009-05-13   74.25   77.71   72.38   73.94   7564720
...            ...     ...     ...     ...       ...
2019-04-25  295.20  295.95  292.85  293.05  10390816
2019-04-26  294.80  296.65  293.50  296.40   6196551
2019-04-30  298.55  299.45  295.00  295.00   7339917
2019-05-02  293.65  298.85  292.65  298.55   4539125
2019-05-03  290.90  293.70  288.55  293.50   7408308

[2469 rows x 5 columns]

In [6]:
data = temp_file.get('/day/NSE/WIPRO').tail(100)['close']

In [10]:
data.values

array([249.36, 250.6 , 245.56, 246.62, 248.16, 254.62, 250.45, 255.34,
       251.92, 256.17, 250.56, 242.18, 245.64, 245.23, 246.2 , 248.16,
       248.76, 245.6 , 244.77, 244.74, 243.95, 243.8 , 244.77, 247.37,
       244.92, 247.14, 235.  , 247.97, 253.05, 252.18, 260.26, 253.98,
       260.53, 264.32, 264.47, 265.75, 267.03, 270.23, 273.12, 277.59,
       279.36, 279.14, 277.03, 279.85, 280.9 , 280.23, 280.49, 281.95,
       283.8 , 282.03, 282.78, 282.41, 273.27, 279.85, 281.62, 284.77,
       289.77, 291.47, 281.5 , 277.37, 282.48, 273.38, 277.45, 268.85,
       257.7 , 259.75, 261.35, 257.9 , 256.85, 263.45, 257.6 , 257.45,
       261.55, 260.55, 256.5 , 255.  , 254.55, 254.75, 254.8 , 261.65,
       261.65, 261.65, 259.05, 262.1 , 263.7 , 273.8 , 281.  , 281.3 ,
       283.4 , 287.7 , 280.9 , 284.8 , 288.25, 291.1 , 293.05, 295.2 ,
       294.8 , 298.55, 293.65, 290.9 ])

In [11]:
from datetime import datetime as dt
from datetime import timedelta

In [2]:
dt.today()

datetime.datetime(2020, 2, 24, 17, 56, 21, 637369)

In [33]:
tmpdata = temp_file.get('/day/NSE/WIPRO')
toDate = tmpdata.index[-1].strftime("%Y-%m-%d")
fromDate = (tmpdata.index[-1] - timedelta(days=10)).strftime("%Y-%m-%d")
data = tmpdata.loc[(tmpdata.index >= fromDate) & (tmpdata.index <= toDate),'close']

In [30]:
toDate+' : '+fromDate

'2019-05-03 : 2019-04-23'

In [34]:
data

date
2019-04-23    291.10
2019-04-24    293.05
2019-04-25    295.20
2019-04-26    294.80
2019-04-30    298.55
2019-05-02    293.65
2019-05-03    290.90
Name: close, dtype: float64

In [9]:
a=25
algo = '''
cache = redis.Redis(host='redis', port=6379)
temp = a+ 20
print(str(temp))
cache.set('temp','123456')
'''
exec(algo)

45

In [7]:
import redis
cache = redis.Redis(host='redis', port=6379)

In [12]:
cache.get('temp').decode("utf-8")

'35'

In [1]:
import sqlalchemy

In [3]:
import sqlalchemy

## Cache Wrappers

In [1]:
import pandas as pd
import numpy as np
from redis import Redis
from datetime import datetime
cache = Redis(host='redis', port=6379, db=0, charset="utf-8", decode_responses=True)
userid = 'suhan'

# Wrapper for Redis cache
class cache_state(Redis):
    def __init__(self, postfix='backtest'):
        Redis.__init__(self, host='redis', port=6379, db=0, charset="utf-8", decode_responses=True)
        self.hash_postfix = postfix
        
    def add(self, key, reset=False):
        hash_key = key+self.hash_postfix
        
        if self.hlen(hash_key) == 0 or reset == True:
            self.hmset(hash_key, {'stock':key, 'qty':0, 'amount':0,'p_n_l':0.0,'Total_p_n_l':0.0,
                                       'low':0.0,'sl':0.0,'ltp':0.0,'tp':0.0,'high':0.0,'last_processed':'1999-01-01',
                                       'state':'INIT','algo':'', 'freq':'min','hdf_freq':'min'})
            # Trade Log: [{timestamp, buy, sale, amount, profit, cum_profit, W_L, Mode}]
            # Amount: -ve for Buy, +ve for sale; W_L: +1 for Win, -1 for Loss; Mode: EN|EX|SL|TP|F
            self.set(hash_key+'Trade', pd.DataFrame().to_json(orient='columns'))
        self.sadd(self.hash_postfix, key)
        
    def getTrades(self, key):
        hash_key = key+self.hash_postfix+'Trade'
        df = pd.read_json(self.get(hash_key))
        return df
    
    def pushTrade(self, key, df):
        hash_key = key+self.hash_postfix+'Trade'
        cache_buff = pd.read_json(conn.get(hash_key))
        cache_buff = cache_buff.append(df)
        conn.set(hash_key, cache_buff.to_json(orient='columns'))
        
    def getValue(self, key='', field=''):
        hash_key = key+self.hash_postfix
        if key == '':
            df = pd.DataFrame()
            for key in self.smembers(self.hash_postfix):
                hash_key = key+self.hash_postfix
                tmp_df = pd.DataFrame([self.hgetall(hash_key)])
                df = df.append(tmp_df, ignore_index=True)
            return df
            
        elif field == '': # return all
            return pd.DataFrame([self.hgetall(hash_key)])
        else:
            return self.hget(hash_key,field)
    
    def setValue(self, key, field, value):
        hash_key = key+self.hash_postfix
        return self.hset(hash_key, field, value)
    
    def remove(self, key=''):
        if key == '':
            for key in self.smembers(self.hash_postfix):
                hash_key = key+self.hash_postfix
                for field in self.hkeys(hash_key):
                    self.hdel(hash_key, field)

                self.srem(self.hash_postfix, key)
            
        else:
            hash_key = key+self.hash_postfix
            for field in self.hkeys(hash_key):
                self.hdel(hash_key, field)

            self.srem(self.hash_postfix, key)
            
    def reset(self, key=''):
        if key == '':
            for key in self.smembers(self.hash_postfix):
                self.add(key,True)
        else:
            self.add(key,True)
            
    def getKeys(self):
        return self.smembers(self.hash_postfix)

In [2]:
conn = Redis(host='redis', port=6379, db=0, charset="utf-8", decode_responses=True)

In [17]:
hash_key = 'TCS'+'backtest'
tmp = list(conn.hkeys(hash_key))
conn.hdel(hash_key, *tmp)

15

In [3]:
cache_backtest = cache_state()

In [4]:
cache_backtest.add('TCS')

In [5]:
cache_backtest.add('WIPRO')

In [20]:
cache_backtest.getValue()

,stock,qty,amount,p_n_l,Total_p_n_l,low,sl,ltp,tp,high,last_processed,state,algo,freq
0,WIPRO,0,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1999-01-01,INIT,,min

In [17]:
cache_backtest.reset()

In [9]:
cache_backtest.reset('TCS')

In [7]:
cache_backtest.setValue('TCS','amount',10)
cache_backtest.setValue('WIPRO','amount',10)

0

In [19]:
cache_backtest.remove('TCS')

In [127]:
conn.smembers('backtest')

set()

In [40]:
cache_backtest.getKeys()

{'WIPRO'}

In [ ]:
# OHLC_cache
# Wrapper for Redis cache
class cache_ohlc(Redis):
    def __init__(self, postfix='ohlc', freq='min'):
        Redis.__init__(self, host='redis', port=6379, db=0, charset="utf-8", decode_responses=True)
        self.hash_postfix = postfix
    
    def msg_to_ohlc(self, data):
        ohlc_list = list(data.values())[0]['ohlc']
        sdate = ohlc_list['date']
        shigh = ohlc_list['high']
        slow = ohlc_list['low']
        sopen = ohlc_list['open']
        sclose = ohlc_list['close']
        svolume = ohlc_list['volume']

        temp_df = pd.DataFrame(ohlc_list, columns=['open','high','low','close','volume'], 
                               index=[datetime.strptime(ohlc_list['date'],'%Y-%m-%d %H:%M:%S')])

        return temp_df
    
    def add(self, key, freq='min', reset=False):
        hash_key = key+self.hash_postfix+freq
        
        if self.exists(hash_key) == 0 or reset == True:
            self.set(hash_key, pd.DataFrame().to_json(orient='columns'))
        self.sadd(self.hash_postfix, key)

    
    def pushOHLC(self, key, ohlc, freq='min'):
        hash_key = key+self.hash_postfix+freq
        pass
    
    def getOHLC(self, key, freq='min'):
        hash_key = key+self.hash_postfix+freq
        pass
    
    
    def remove(self, key=''):
        if key == '':
            for key in self.smembers(self.hash_postfix):
                hash_key = key+self.hash_postfix
                self.del(hash_key)

                self.srem(self.hash_postfix, key)
            
        else:
            hash_key = key+self.hash_postfix
            self.del(hash_key)

            self.srem(self.hash_postfix, key)
            
    def reset(self, key=''):
        if key == '':
            for key in self.smembers(self.hash_postfix):
                self.add(key,True)
        else:
            self.add(key,True)
            
    def getKeys(self):
        return self.smembers(self.hash_postfix)

In [152]:
df1 = pd.DataFrame([{'date':'2019-05-02 09:20:00','open':12.5,'high':15,'low':10,'close':10}]).set_index('date')
df2 = pd.DataFrame([{'date':'2019-05-02 09:25:00','open':12.5,'high':15,'low':10,'close':10}]).set_index('date')

In [171]:
dict1 = json.dumps({'date':'2019-05-02 09:20:00','open':12.5,'high':15,'low':10,'close':10})
conn.rpush('TCSohlc',dict1)
conn.rpush('TCSohlc',dict1)
conn.rpush('TCSohlc',dict1)
conn.rpush('TCSohlc',dict1)

4

In [153]:
import json
conn.rpush('TCSohlc',df1.to_json())
conn.rpush('TCSohlc',df2.to_json())
#conn.rpush('TCSohlc',df.to_json())
#conn.rpush('TCSohlc',df.to_json())

2

In [172]:
conn.llen('TCSohlc')

4

In [136]:
conn.lpop('TCSohlc')

'{"open":{"2019-05-02 09:20:00":12.5},"high":{"2019-05-02 09:20:00":15},"low":{"2019-05-02 09:20:00":10},"close":{"2019-05-02 09:20:00":10}}'

In [180]:
conn.lrange('TCSohlc',0,10)

['{"date": "2019-05-02 09:20:00", "open": 12.5, "high": 15, "low": 10, "close": 10}',
 '{"date": "2019-05-02 09:20:00", "open": 12.5, "high": 15, "low": 10, "close": 10}',
 '{"date": "2019-05-02 09:20:00", "open": 12.5, "high": 15, "low": 10, "close": 10}',
 '{"date": "2019-05-02 09:20:00", "open": 12.5, "high": 15, "low": 10, "close": 10}']

In [ ]:
pd.read_json(tmp[1:2])

In [163]:
pd.DataFrame([{'date':'2019-05-02 09:20:00','open':12.5,'high':15,'low':10,'close':10},{'date':'2019-05-02 09:20:00','open':12.5,'high':15,'low':10,'close':10}])

                  date  open  high  low  close
0  2019-05-02 09:20:00  12.5    15   10     10
1  2019-05-02 09:20:00  12.5    15   10     10

In [166]:
conn.ltrim('TCSohlc',0,0)
conn.lpop('TCSohlc')